export default {
  ON_LOGIN_FAILED: 'ON_LOGIN_FAILED',
  ON_LOGIN_SUCCESS: 'ON_LOGIN_SUCCESS',
  ON_LOGIN: 'ON_LOGIN',
  ON_REGISTER: 'ON_REGISTER',
  ON_LOGOUT: 'ON_LOGOUT',
  CLEAR_ERROR: 'CLEAR_ERROR'
};
