export default {
    ON_LOGIN_OR_REGISTER_FAILED: "ON_LOGIN_OR_REGISTER_FAILED",
    ON_LOGIN_OR_REGISTER_SUCCESS: "ON_LOGIN_OR_REGISTER_SUCCESS",
    ON_LOGIN: "ON_LOGIN",
    ON_REGISTER: "ON_REGISTER",
    ON_LOGOUT: "ON_LOGOUT"
  };
  